#!/usr/bin/env node
// Generated by LiveScript 1.3.1
(function(){
  var docopt, _, ref$, cat, mkdir, rm, exec, v, uid, Promise, asyncrepl, process, modulePath, fs, doc, getOption, o, targetMode, FILE, text;
  docopt = require('docopt').docopt;
  _ = require('lodash');
  ref$ = require('shelljs'), cat = ref$.cat, mkdir = ref$.mkdir, rm = ref$.rm, exec = ref$.exec;
  v = require('verbal-expressions');
  uid = require('uid');
  Promise = require('bluebird');
  asyncrepl = require('async-replace');
  process = require('./index').process;
  modulePath = "";
  fs = require('fs');
  doc = "Usage:\n    exemd FILE [ -r | --raw ] [ -g | --force-png ] [ -p | --pdf ]\n    exemd -h | --help \n\nOptions:\n    -g, --force-png     Force png generation\n    -r, --raw           Unfold and execute blocks, generate raw markdown\n    -p, --pdf           Generate raw markdown with external figures, to be proc. with latex \n    -h, --help  \n\nArguments: \n    FILE       markdown file name.\n";
  getOption = function(a, b, def, o){
    if (!o[a] && !o[b]) {
      return def;
    } else {
      return o[b];
    }
  };
  o = docopt(doc);
  if (o['-g'] || o['--force-png']) {
    targetMode = 'html,png';
  } else {
    if (o['--raw'] || o['-r']) {
      targetMode = 'raw,png';
    } else {
      if (o['-p'] || o['--pdf']) {
        targetMode = 'raw,pdf';
      } else {
        targetMode = 'html';
      }
    }
  }
  FILE = o['FILE'];
  text = cat(FILE);
  process(targetMode, text).then(function(it){
    return console.log(it);
  });
}).call(this);
