# Makefile autogenerated by Dyi on March 18, 2015
#
# Main target: all
# Sources:  command.ls  index.ls 

.DEFAULT_GOAL := all


.PHONY: c-laq5j643
c-laq5j643: command.js index.js


.PHONY: docs
docs: k-wewkw3tk


.PHONY: build
build: c-laq5j643 docs


.PHONY: test
test: k-tptik4k2


.PHONY: up
up: k-tcqym7h4


.PHONY: major
major: k-a7q2a6jp


.PHONY: minor
minor: k-t93ndoq3


.PHONY: patch
patch: k-6fk61fu6


.PHONY: prepare
prepare: .




.PHONY: k-wewkw3tk
k-wewkw3tk:  
	./node_modules/.bin/verb


.PHONY: k-7c6ruvdj
k-7c6ruvdj:  
	((echo '#!/usr/bin/env node') && cat command.js) > cli.js


.PHONY: k-67fs0utd
k-67fs0utd:  
	chmod +x ./cli.js


.PHONY: all
all: 
	make build 
	make k-7c6ruvdj 
	make k-67fs0utd  


.PHONY: k-tptik4k2
k-tptik4k2:  
	./test/test.sh


.PHONY: k-tcqym7h4
k-tcqym7h4:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-a7q2a6jp
k-a7q2a6jp:  
	./node_modules/.bin/xyz -i major


.PHONY: k-t93ndoq3
k-t93ndoq3:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-6fk61fu6
k-6fk61fu6:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f command.js
	rm -f index.js


.PHONY: update
update: 
	make clean   
	node




command.js: command.ls 
	lsc -c command.ls

index.js: index.ls 
	lsc -c index.ls

.: 
	mkdir -p .

