# Makefile autogenerated by Dyi on March 18, 2015
#
# Main target: all
# Sources:  command.ls  index.ls 

.DEFAULT_GOAL := all


.PHONY: c-3c79ev81
c-3c79ev81: command.js index.js


.PHONY: build
build: c-3c79ev81


.PHONY: docs
docs: k-jc0qe6un


.PHONY: test
test: k-h8r7shtb


.PHONY: up
up: k-yfpayvtf


.PHONY: major
major: k-0h0rw9wp


.PHONY: minor
minor: k-5ueqvcla


.PHONY: patch
patch: k-mr3i29nk


.PHONY: prepare
prepare: .




.PHONY: k-a7wawriy
k-a7wawriy:  
	((echo '#!/usr/bin/env node') && cat command.js) > cli.js


.PHONY: k-4tasrn4k
k-4tasrn4k:  
	chmod +x ./cli.js


.PHONY: all
all: 
	make build 
	make k-a7wawriy 
	make k-4tasrn4k  


.PHONY: k-jc0qe6un
k-jc0qe6un:  
	./node_modules/.bin/verb


.PHONY: k-h8r7shtb
k-h8r7shtb:  
	./test/test.sh


.PHONY: k-yfpayvtf
k-yfpayvtf:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-0h0rw9wp
k-0h0rw9wp:  
	./node_modules/.bin/xyz -i major


.PHONY: k-5ueqvcla
k-5ueqvcla:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-mr3i29nk
k-mr3i29nk:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f command.js
	rm -f index.js


.PHONY: update
update: 
	make clean   
	node




command.js: command.ls 
	lsc -c command.ls

index.js: index.ls 
	lsc -c index.ls

.: 
	mkdir -p .

